services:
  - type: web
    name: truthchecker-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5001
      - key: MONGODB_URI
        value: your_mongodb_connection_string
      - key: JWT_SECRET
        value: your_secret_key
